FROM docker.io/rust:1.88-bookworm AS builder

WORKDIR /build
COPY ./Cargo.toml ./Cargo.lock ./VERSION /build/
RUN cargo fetch
COPY ./src/ /build/src
ENV RUSTFLAGS="-C target-cpu=native"
RUN cargo build --release

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*
COPY --from=builder /build/target/release/nano-web /usr/local/bin/nano-web
COPY ./public /public
EXPOSE 3000
CMD ["/usr/local/bin/nano-web", "serve", "/public", "--port", "3000"]
