[workspace]
# Don't publish to crates.io automatically - CI will handle it
publish = false
# Let cargo-release handle git tag and push to trigger CI
push = true
tag = true

# Update version in VERSION file and Cargo.toml
pre-release-replacements = [
  { file = "VERSION", search = "^[0-9\\.]+", replace = "{{version}}" },
  { file = "CHANGELOG.md", search = "## \\[Unreleased\\]", replace = "## [Unreleased]\n\n## [{{version}}] - {{date}}", exactly = 1 },
]

# Only do the version bump and file updates
pre-release-commit-message = "Bump version to {{version}}"
no-dev-version = true