version: '3'

env:
  PKGOS: linux
  PKGARCH: amd64
  PKGNAME: nano-web
  RELEASEDIR: ./release
  CGO_ENABLED: 0

vars:
  VERSION:
    sh: git describe --tags --abbrev=0 2>/dev/null | sed 's/v//' || echo "dev"
  COMMIT:
    sh: git rev-parse --short HEAD
  BUILD_TIME:
    sh: date -u +"%Y-%m-%dT%H:%M:%SZ"
  LDFLAGS: -s -w -X main.version={{.VERSION}} -X main.commit={{.COMMIT}} -X main.buildTime={{.BUILD_TIME}}
  PKGRELEASE: "{{.PKGNAME}}_{{.VERSION}}"
  PKGDIR: "{{.RELEASEDIR}}/{{.PKGRELEASE}}-{{.PKGARCH}}"

tasks:
  default:
    desc: "Show available tasks"
    cmd: task --list

  dev:
    desc: "🚀 Run development server"
    deps: [build]
    cmd: ./{{.PKGNAME}} serve --port 8080 --log-format console --log-level debug

  run:
    desc: "🏃 Run with go run"
    cmd: go run main.go serve --port 8080 --log-format console --log-level debug

  build:
    desc: "🏗️ Build binary"
    sources:
      - "*.go"
      - "go.mod"
      - "go.sum"
    generates:
      - "{{.PKGNAME}}"
    cmd: go build -ldflags="{{.LDFLAGS}}" -o {{.PKGNAME}} main.go

  build-all:
    desc: "🌍 Build for all platforms"
    deps: [clean-dist]
    cmds:
      - mkdir -p dist
      - GOOS=linux GOARCH=amd64 go build -ldflags="{{.LDFLAGS}}" -o dist/{{.PKGNAME}}-linux-amd64 main.go
      - GOOS=linux GOARCH=arm64 go build -ldflags="{{.LDFLAGS}}" -o dist/{{.PKGNAME}}-linux-arm64 main.go
      - GOOS=darwin GOARCH=amd64 go build -ldflags="{{.LDFLAGS}}" -o dist/{{.PKGNAME}}-darwin-amd64 main.go
      - GOOS=darwin GOARCH=arm64 go build -ldflags="{{.LDFLAGS}}" -o dist/{{.PKGNAME}}-darwin-arm64 main.go
      - GOOS=windows GOARCH=amd64 go build -ldflags="{{.LDFLAGS}}" -o dist/{{.PKGNAME}}-windows-amd64.exe main.go
      - GOOS=freebsd GOARCH=amd64 go build -ldflags="{{.LDFLAGS}}" -o dist/{{.PKGNAME}}-freebsd-amd64 main.go

  test:
    desc: "🧪 Run tests"
    cmd: go test -v -race ./...

  test-coverage:
    desc: "📊 Run tests with coverage"
    cmds:
      - go test -v -race -coverprofile=coverage.out -covermode=atomic ./...
      - go tool cover -html=coverage.out -o coverage.html
      - echo "Coverage report generated coverage.html"

  bench:
    desc: "🔥 Run benchmarks"
    cmd: go test -bench=. -benchmem -count=3 ./...

  lint:
    desc: "🔍 Run linter"
    cmd: golangci-lint run

  fmt:
    desc: "✨ Format code"
    cmds:
      - go fmt ./...
      - goimports -w .

  vet:
    desc: "🔎 Run go vet"
    cmd: go vet ./...

  check:
    desc: "✅ Run all checks"
    cmds:
      - task: test
      - task: lint
      - task: vet

  deps:
    desc: "📦 Download dependencies"
    cmd: go mod download

  deps-update:
    desc: "⬆️ Update dependencies"
    cmds:
      - go get -u ./...
      - go mod tidy

  clean:
    desc: "🧹 Clean build artifacts"
    cmds:
      - rm -f {{.PKGNAME}}
      - rm -f coverage.out coverage.html

  clean-dist:
    desc: "🗑️ Clean dist directory"
    cmd: rm -rf dist/

  clean-all:
    desc: "💥 Clean everything"
    deps: [clean, clean-dist, pkg-clean]

  docker-build:
    desc: "🐳 Build Docker image"
    cmd: docker build -t {{.PKGNAME}}:{{.VERSION}} -t {{.PKGNAME}}:latest .

  docker-run:
    desc: "🚢 Run Docker container"
    deps: [docker-build]
    cmd: docker run --rm -p 8080:8080 -e PORT=8080 {{.PKGNAME}}:latest

  release-local:
    desc: "🚀 Create local release"
    deps: [build-all]
    cmds:
      - mkdir -p {{.RELEASEDIR}}
      - cd dist && for file in {{.PKGNAME}}-*; do tar -czf ../{{.RELEASEDIR}}/$file.tar.gz $file; done
      - cd {{.RELEASEDIR}} && sha256sum *.tar.gz > checksums.txt
      - echo "Local release created in release dir"

  pkg-clean:
    desc: "🧹 Clean package artifacts"
    cmd: rm -rf {{.RELEASEDIR}}

  pkg-build:
    desc: "📦 Build OPS package binary"
    env:
      GOOS: "{{.PKGOS}}"
      GOARCH: "{{.PKGARCH}}"
    cmd: |
      mkdir -p {{.PKGDIR}}
      go build -ldflags="{{.LDFLAGS}}" -o {{.PKGDIR}}/{{.PKGNAME}} main.go

  pkg-create:
    desc: "📁 Create OPS package structure"
    deps: [pkg-clean]
    cmds:
      - mkdir -p {{.PKGDIR}}/sysroot/public
      - |
        cat > {{.PKGDIR}}/package.manifest << EOF
        {
           "Program":"{{.PKGRELEASE}}/{{.PKGNAME}}",
           "Args" : ["{{.PKGNAME}}", "serve"],
           "Version":"{{.VERSION}}"
        }
        EOF
      - cp README.md {{.PKGDIR}}/

  pkg-add:
    desc: "➕ Add OPS package"
    deps: [pkg-create, pkg-build]
    cmd: ops pkg add {{.PKGDIR}} --name {{.PKGRELEASE}}

  pkg-bundle:
    desc: "📦 Bundle OPS package"
    deps: [pkg-add]
    cmds:
      - cd {{.RELEASEDIR}} && tar czvf {{.PKGRELEASE}}-{{.PKGARCH}}.tar.gz {{.PKGRELEASE}}-{{.PKGARCH}}
      - echo "Package bundle created"

  pkg-push:
    desc: "📤 Push OPS package"
    deps: [pkg-add]
    cmd: ops pkg push {{.PKGRELEASE}}

  pkg-load:
    desc: "🚀 Load and run OPS package"
    deps: [pkg-add]
    cmd: ops pkg load -l {{.PKGRELEASE}} -p 80

  health:
    desc: "🩺 Run health check"
    deps: [build]
    cmd: ./{{.PKGNAME}} health-check

  version:
    desc: "📋 Show version"
    cmd: echo "Version {{.VERSION}} Commit {{.COMMIT}} Built {{.BUILD_TIME}}"

  info:
    desc: "ℹ️ Show project info"
    cmds:
      - echo "Project {{.PKGNAME}}"
      - echo "Version {{.VERSION}}"
      - echo "Commit {{.COMMIT}}"
      - echo "Build Time {{.BUILD_TIME}}"
      - go version
      - echo "Platform {{OS}}/{{ARCH}}"

  tag:
    desc: "🏷️ Create git tag"
    vars:
      TAG: "{{.CLI_ARGS}}"
    preconditions:
      - sh: '[ -n "{{.TAG}}" ]'
        msg: "Please provide a tag: task tag -- v1.0.0"
    cmds:
      - git tag -a {{.TAG}} -m "Release {{.TAG}}"
      - echo "Created tag {{.TAG}}"
      - echo "Push with git push origin {{.TAG}}"

  ci:
    desc: "🤖 Run CI pipeline"
    cmds:
      - task: deps
      - task: check
      - task: build-all
      - echo "CI completed successfully"