# Cargo aliases for common development tasks
# Usage: cargo dev, cargo serve, cargo check-all, etc.

[alias]
dev = "run -- --dev --port 3000 --log-format console --log-level debug"
serve = "run --"
build-release = "build --release"
check-all = ["check", "test", "clippy"]
fmt-all = "fmt"
bench = "bench"
clean-all = "clean"

# Target-specific configurations
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.aarch64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]