name: OPS Package (amd64)

permissions:
  contents: read

on:
  push:
    tags:
      - v*
jobs:
  test:
    uses: ./.github/workflows/test.yml

  publish:
    needs: test
    uses: radiosilence/nano-web/.github/workflows/push-package.yml@main
    with:
      arch: amd64
    secrets:
      OPS_KEY: ${{ secrets.OPS_KEY }}
