name: Publish Package

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
    secrets:
      OPS_KEY:
        required: true

jobs:
  publish:
    name: Build & Push Package for (${{ inputs.arch }})
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up OPS
        run: |
          curl https://ops.city/get.sh -sSfL | sh
      - name: Set OPS environment variables
        run: |
          echo "OPS_DIR=$HOME/.ops" >> $GITHUB_ENV
          echo "$HOME/.ops/bin" >> $GITHUB_PATH
      - name: Login
        run: |
          ops pkg login ${{ secrets.OPS_KEY }}
      - name: Push
        run: |
          echo "Version: $(./scripts/get-version.sh)"
          make pkg-push PKGARCH=${{ inputs.arch }}
